apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: basic-cluster # eks 이름
  region: ap-northeast-2
  version: "1.24" # 쿠버네티스 버전

vpc:
  cidr: "10.0.0.0/16" # eks클러스터에서 사용할 VPC의 CIDR
  clusterEndpoints:
    privateAccess: true
    publicAccess: true

managedNodeGroups:
  - name: node-group-a
    instanceType: t3.small
    desiredCapacity: 1
    volumeSize: 10
    privateNetworking: true

cloudWatch:
  clusterLogging:
    enableTypes: ["api", "audit", "authenticator", "controllerManager", "scheduler"]
    logRetentionInDays: 1