apiVersion: v1
kind: Pod
metadata:
  name: busybox-pod
spec:
  containers:
  - name: busybox
    image: busybox
    resources:
      requests:
        cpu: "100m"
        memory: "64Mi"
      limits:
        cpu: "100m"
        memory: "64Mi"
    args:
    - /bin/sh
    - -c
    - >
      while true; do
        echo "Hello World!";
        sleep 1;
      done
